import type { Metadata } from "next";
import Link from "next/link";
import Breadcrumbs from "@/components/ui/Breadcrumbs";
import SchemaOrg from "@/components/ui/SchemaOrg";
import { buildArticleSchema } from "@/lib/seo-config";
export const metadata: Metadata = { title: "Comment s'Habiller pour un Enterrement Musulman ? Guide Complet", description: "Quelle tenue adopter pour un enterrement musulman ? Couleurs, habits appropriés, ce qu'il faut éviter. Guide complet pour hommes et femmes.", keywords: ["enterrement islam vêtement", "comment s'habiller enterrement musulman", "tenue enterrement musulman", "tenue deuil islamique"] };
export default function Page() { return (<div className="bg-[#F5F0E8] text-[#1A1A1A] min-h-screen font-inter"><SchemaOrg data={buildArticleSchema({ headline: "Comment s'Habiller pour un Enterrement Musulman ?", datePublished: "2024-03-15" })} /><section className="relative w-full pt-28 pb-16 bg-[#0D1208] text-white"><div className="relative z-10 w-full max-w-[1280px] mx-auto px-8 md:px-12"><Breadcrumbs items={[{ label: "Guide", href: "/guide" }, { label: "Vêtements Enterrement", href: "/guide/enterrement-islam-vetement" }]} /><h1 className="text-[2.2rem] md:text-[3rem] font-semibold leading-[1.1] tracking-[-0.02em] text-white mb-6 mt-6 max-w-[700px]">Comment s&apos;Habiller pour un Enterrement Musulman ?</h1></div></section><section className="w-full bg-[#F5F0E8] py-20 md:py-28"><div className="w-full max-w-[1280px] mx-auto px-8 md:px-12"><div className="max-w-[780px]">
  <h2 className="text-[24px] font-semibold text-[#1A1A1A] mb-6">Les règles vestimentaires pour un enterrement musulman</h2>
  <p className="text-[15px] font-light text-[#555] leading-[1.8] mb-8">L&apos;Islam recommande la sobriété et la pudeur dans la tenue vestimentaire lors d&apos;un enterrement musulman. Il n&apos;y a pas d&apos;obligation de porter du noir — contrairement à la tradition occidentale. Les couleurs neutres et sombres sont néanmoins appropriées par respect.</p>
  <h2 className="text-[24px] font-semibold text-[#1A1A1A] mb-6">Pour les hommes</h2>
  <ul className="flex flex-col gap-2 mb-8">{["Vêtements propres et sobres (couleurs neutres : blanc, gris, noir, marron)", "Éviter les couleurs vives et les motifs extravagants", "Chaussures propres", "Se couvrir les épaules et les genoux"].map((t,i)=>(<li key={i} className="flex items-start gap-3 text-[14.5px] text-[#555] font-light"><span className="w-1.5 h-1.5 rounded-full bg-[#2D6A2D] mt-2 shrink-0"/>{t}</li>))}</ul>
  <h2 className="text-[24px] font-semibold text-[#1A1A1A] mb-6">Pour les femmes</h2>
  <ul className="flex flex-col gap-2 mb-8">{["Tenue ample et pudique couvrant le corps", "Hijab ou voile couvrant les cheveux", "Couleurs sobres (noir, blanc, gris, bleu marine)", "Éviter le maquillage et les parfums forts", "Chaussures fermées et sobres"].map((t,i)=>(<li key={i} className="flex items-start gap-3 text-[14.5px] text-[#555] font-light"><span className="w-1.5 h-1.5 rounded-full bg-[#2D6A2D] mt-2 shrink-0"/>{t}</li>))}</ul>
  <p className="text-[15px] font-light text-[#555] leading-[1.8] mb-4">Pour en savoir plus sur les <Link href="/guide/rites-funeraires-islam-etapes" className="text-[#2D6A2D] font-medium hover:underline">rites funéraires islamiques</Link> et les <Link href="/guide/condoleances-islam" className="text-[#2D6A2D] font-medium hover:underline">condoléances en Islam</Link>.</p>
</div></div></section></div>); }
